import express from 'express';
import { signUpWithGoogle } from '../controllers/SignUpwithGoogle';
import { CreatAccount } from '../controllers/CreateAccount';
import { CreateUser } from '../controllers/CreateUser';
import { DeleteUser } from '../controllers/DeleteUser';
import { signUpWithEmail } from '../controllers/SignUpWithEmail';
import { resendOTP } from '../controllers/ResendOTP';
import { LoginWithEmail } from '../controllers/LoginWithEmail';
import { LoginWithGoogle } from '../controllers/LoginWithGmail';
export const signupRouter = express.Router();
signupRouter.post('/signup-google', signUpWithGoogle);
signupRouter.post('/create-account', CreatAccount);
signupRouter.post('/create-user', CreateUser);
signupRouter.delete('/delete-user', DeleteUser);
signupRouter.post('/signup-email', signUpWithEmail);
signupRouter.post('/resend-otp', resendOTP);
signupRouter.post('/verify-otp', resendOTP);
