version: '3.9'

services:
  postgres_auth:
    image: postgres:14-alpine
    ports:
      - 5020:5432
    volumes:
      - ~/apps/postgres_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

    
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
